/**
 * TinaCMS admin UI — served as static files generated by `tinacms build`.
 * The actual admin HTML/JS lives in public/admin/ after running:
 *   pnpm tina:build
 * This page component is a thin wrapper that ensures Next.js doesn't intercept
 * the /admin route; the static files from public/ take precedence in production.
 *
 * In local dev (`pnpm tina:dev`), TinaCMS dev server proxies /admin itself.
 */
export default function AdminPage() {
  return null
}

export function generateStaticParams() {
  return []
}
